using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sequor.Domain.Enumerables.EnumerablesLES
{    
    public enum STATUS_FOLHA_ROSTO
    {
        CODIGO_RESERVADO = 5,
        CANCELADA = 6,
        CONFIRMADA = 7,
        FOLHAROSTO_E_VOLUMES_GERADOS = 10,
        FOLHAROSTO_E_VOLUMES_GERADOS_SEM_PRERECEBIMENTO = 12,
        ENTRADA_AUTORIZADA = 15,
        ENTRADA_REALIZADA = 16,
        INSPEÇÃO_VOLUMES_INICIADA = 20,
        INSPEÇÃO_VOLUMES_PARCIAL = 30,
        INSPECAO_VOLUMES_FALTA = 35,
        INSPECAO_VOLUMES_SOBRA = 40,
        VOLUMES_INSPECIONADOS = 50,
        ENTRADA_AUTORIZADA_SEM_PReRECEBIMENTO = 55,
        ENTRADA_REALIZADA_SEM_PRERECEBIMENTO = 56,
        INSPECAO_ITENS_INICIADA = 60,
        FOLHA_ROSTO_EM_UTILIZACAO = 61,
        INSPECAO_ITENS_PARCIAL = 70,
        ITENS_INSPECIONADOS = 80,
        ITENS_INSPECIONADOS_RECONTAGEM = 85,
        ITENS_INSPECIONADOS_DIVERGENCIA = 90,
        ANALISE_DIVERGÊNCIA_PRERECEBIMENTO = 100,
        ANALISE_DIVERGÊNCIA_RECEBIMENTO = 110,
        DEVOLUCAO = 120,
        DIVERGENCIA_ENCERRADA = 130,
        SAIDA_VEÍCULO = 150,
        REMOVIDO_ERP = 160,
        ALTERADO_ERP = 170,
        ESTORNADO_ERP = 180
    }
}
